---
title: "2019 Masters"
author: "Tom Kain"
date: "April 11, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(naniar)
library(plotly)
library(tidyverse)
library(rvest)
library(RSelenium)
library(knitr)
url <- "http://www.augusta.com/masters/leaderboard"
```

```{bash engine="sh", eval=FALSE, include=FALSE} 
docker run -d --shm-size=2g -it -p 4445:4444 -p 5901:5900 selenium/standalone-firefox-debug
```

```{r}
refresh_leaderboard_remote <- function() {
  sess <- remoteDriver(
    remoteServerAddr = "192.168.0.246",
    port = 4445L,
    browser = "firefox")

  sess$open()
  sess$navigate(url)
  Sys.sleep(2)
  sess$getPageSource()[[1]] -> html_source
  sess$close()
  
  html_source
}

refresh_leaderboard_local <- function() {
  sess <- rsDriver(
    remoteServerAddr = "192.168.99.100",
    port = 4445L,
    verbose = FALSE, 
    browser = "firefox")

  sess$client$navigate(url)
  Sys.sleep(2)
  sess$client$getPageSource()[[1]] -> html_source
  sess$client$close()
  
  html_source
}

refresh_leaderboard <- function(mode) {
  if (!mode %in% c("local","remote")) {
    stop("invalid mode")
  } else if (mode == "local") {
    html_source <- refresh_leaderboard_local()
  } else {
    html_source <- refresh_leaderboard_remote()
  }
  
  html_source %>% 
    read_html() %>% 
    html_nodes("table") %>% 
    .[[1]] %>% 
    html_table(fill=TRUE) %>% 
    as_tibble() -> leaderboard
  
  draft_picks <- read_csv("data/picks.csv") %>% 
    clean_names() %>% 
    rename(draft_pick = pick)
  
  leaderboard[3,] -> colnames(leaderboard)
  
  leaderboard[-(1:3),] %>% 
    clean_names() %>% 
    rename(strokes = total_2) %>%  
    replace_with_na_all(condition = ~.x == "") %>% 
    filter(name != "0", !is.na(name))-> leaderboard
  
  leaderboard[is.na(leaderboard)] <- 0
  
  left_join(leaderboard, draft_picks, by = "name") -> leaderboard
  
  filename <- paste0("data/leaderboard_",Sys.Date(),".csv")
  leaderboard %>% write_csv(filename)
  
  leaderboard
}
```

```{r}
mode <- "remote"

refresh_leaderboard(mode) -> leaderboard
```

```{r}
leaderboard_calc <- leaderboard %>% 
  mutate(total = if_else(total == "E",0,total %>% as.numeric()),
         today = if_else(today == "E",0,today %>% as.numeric()),
         draft_round = ceiling(draft_pick/3)) %>% 
  rename(r1_strokes = r1,
         r2_strokes = r2) %>% 
  mutate(r1_strokes = as.numeric(r1_strokes),
         r2_strokes = as.numeric(r2_strokes),
         r1 = r1_strokes - 72,
         r2 = r2_strokes - 72)
```

```{r}
leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  group_by(inverted, draft_round) %>% 
  summarize(r1 = sum(r1),
            r2 = sum(r2)) %>% 
  arrange(draft_round) -> score_by_draft_and_tourney_round
  

leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  arrange(inverted) %>% 
  select(name, total, r1:r2, player, inverted, draft_round) %>% 
  arrange(total) -> draft_leaderboard_by_round


leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  group_by(player, inverted) %>% 
  summarize(r1 = sum(r1),
            total = sum(total)) %>% 
  gather(round, score, r1:total) %>% 
  spread(player, score) -> draft_aggregate_by_round
  

leaderboard_calc %>%
  gather(round, score, c(r1:r2, total)) %>% 
  ggplot(aes(y=score,x=round,color=player)) +
  geom_jitter(aes(text=name), width=.2, height = 0) +
  scale_y_reverse() -> rounds_plot

ggplotly(rounds_plot)
```



```{r }
leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  group_by(inverted, draft_round) %>% 
  summarize(today = sum(today),
            total = sum(total)) %>% 
  arrange(draft_round) -> score_by_draft_round 
  

leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  arrange(inverted) %>% 
  select(pos:total, today, thru, player, inverted, draft_round) -> draft_leaderboard


leaderboard_calc %>% 
  filter(!is.na(player)) %>% 
  group_by(player, inverted) %>% 
  summarize(total = sum(total)) %>% 
  spread(player, total) -> draft_aggregate_score

```

```{r}
score_by_draft_and_tourney_round 
draft_leaderboard_by_round 
draft_aggregate_by_round 
score_by_draft_round 
draft_leaderboard 
draft_aggregate_score 

#TODO add round score-to-date columns (currently have isolated daily performance)
#TODO try animating the score-to-date columns in a plot
```