---
title: "After the second round"
author: "Tom Kain"
date: "1/13/2019"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(DT)
library(magrittr)
library(googlesheets)
library(tidyverse)
```

```{r import, message=FALSE}
raw_df <- read_csv('outcomes_analysis1.csv') %>%
  filter(
    `AFC Wildcard 1` == "Chargers" &
    `AFC Wildcard 2` == "Colts" &
    `NFC Wildcard 1` == "Cowboys" &
    `NFC Wildcard 2` == "Eagles" &
    `AFC Divisional 1` == 'Chiefs',
    `AFC Divisional 2` == 'Pats',
    `NFC Divisional 1` == 'Saints',
    `NFC Divisional 2` == 'Rams'
    ) %>%
  select(-(`AFC Wildcard 1`:`AFC Divisional 2`), 
         -(`NFC Wildcard 1`:`NFC Divisional 2`))
raw_df %>%
  summarize(p = sum(p)) %>%
  pull() -> p_sum
init_df <- raw_df %>%
  mutate(p_adj = p * 1/p_sum)
```

```{r afterround2}

init_df %>%
  count(Winner)

init_df %>%
  filter(Winner != 'Will') %>%
  select(`AFC Championship`, `NFC Championship`, `Super Bowl`) %>%
  datatable()

```

After two rounds, there are 8 scenarios left, and only two where Will doesn't win outright. Dad needs a Pats/Saints super bowl to force a tie and Tom to make a tie breaker. 
