---
title: "Divisional Futures"
author: "Tom Kain"
date: "April 1, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
library(plotly)
library(tidyverse)
library(janitor)
library(knitr)
library(glue)
source("R/standings.R")
```
## Draft Results and Preseason Projections
```{r}
picks <- read_csv("data/2019_mlbFutures_picks.csv") %>% 
  clean_names() %>% 
  mutate(pick = row_number(),
         round = (pick / 3) %>% ceiling())

colors <- read_csv("data/team_colors.csv")
```
```{r}
preseason_proj <- picks %>%
  mutate(avg_wins = (proj_538 + proj_fangraphs) / 2,
         points_proj = case_when(
           inverted ~ 162 - avg_wins,
           TRUE ~ avg_wins
         )) %>% 
  left_join(colors, by = "team")
```
```{r}
preseason_proj %>% 
  mutate(player = fct_reorder(player, pick),
         invert_display = if_else(inverted, " (Inverted)", ""),
         team = glue("{team} - {division}{invert_display}")) %>% 
  select(player, round, team) %>% 
  spread(player, team) 

preseason_proj_by_round <- preseason_proj %>% 
  mutate(player = fct_reorder(player, pick)) %>% 
  select(player, round, points_proj) %>%
  spread(player, points_proj) %>% 
  mutate(round = round %>% as.character())

preseason_proj_by_round %>% 
  select(-round) %>% 
  summarise_all(sum) %>% 
  mutate(round = "Total") %>%
  bind_rows(preseason_proj_by_round) %>% 
  select(round, Tom:Dad) %>% 
  arrange(round) 

```

```{r}
weekly_standings <- get_weekly_standings()
```

```{r}
picks_trend <- preseason_proj %>% 
  select(-division) %>% 
  left_join(weekly_standings, by = c("abbrev" = "tm")) %>% 
  mutate(points = if_else(inverted,l,w),
         w_pace = round_half_up(w_l_percent * 162),
         l_pace = 162-w_pace,
         points_pace = if_else(inverted,l_pace,w_pace),
         w_pyth = round_half_up(pyth_w_l_percent * 162),
         l_pyth = 162-w_pyth,
         points_pyth = if_else(inverted,l_pyth,w_pyth))

picks_latest <- picks_trend %>% 
  filter(as_of == Sys.Date())

picks_latest %>% 
  group_by(player) %>% 
  summarize_at(vars(points, points_proj, points_pace, points_pyth), sum) -> standings_df
```

```{r}
# TODO lineup with this? https://www.datanovia.com/en/blog/how-to-create-a-ggplot-stacked-bar-chart-2/ or this? https://stackoverflow.com/questions/6644997/showing-data-values-on-stacked-bar-chart-in-ggplot2
preseason_plot_df <- preseason_proj %>% 
  mutate(player = fct_reorder(player, pick)) %>% 
  mutate(team = fct_reorder2(team, desc(points_proj), round)) %>%
  arrange(desc(points_proj)) %>% 
  group_by(player) %>% 
  mutate(pos = cumsum(points_proj) - points_proj/2) %>% 
  ungroup()

cols <- preseason_plot_df$color1
names(cols) <- preseason_plot_df$team

label_cols <- preseason_plot_df$color2
names(label_cols) <- preseason_plot_df$team

preseason_plot_df %>% 
  ggplot(aes(x=player, y=points_proj, fill=team)) +
  geom_col(aes(text=team), position = "stack") +
  scale_fill_manual(values=cols)  -> t

ggplotly(t)
```

```{r}
trend_summary <- picks_trend %>% 
  mutate(games = w+l,
         points_proj_as_of = points_proj / (162/games),
         points_pyth_as_of = points_pyth / (162/games)) %>% 
  group_by(as_of, player) %>% 
  summarize_at(vars(points, points_proj_as_of, points_pyth_as_of, games), sum) %>% 
  mutate(progress = paste0(round_half_up(games / (162*5)*100),"%"))

trend_summary %>% 
  ggplot(aes(x=as_of,group=player,color=player)) +
  geom_line(aes(y=points)) +
  geom_line(aes(y=points_proj_as_of), linetype="longdash") +
  geom_line(aes(y=points_pyth_as_of), linetype="dotdash", alpha = .5) +
  theme(legend.position = "none") +
  labs(y="",x="") +
  facet_wrap(~ player) -> trend_plot
```

```{r echo=FALSE, include=TRUE}
standings_df %>% knitr::kable()
trend_plot
```

#### To Do

1. Abstract the plotting so that it can be displayed for current and various projected point totals
2. Team-by-team trend visual
3. Some way to look ahead at upcoming matchups, including potential points in play, best case scenarios, etc

```{r}
picks_trend %>% 
  ggplot(aes(x=as_of,group=team,color=team)) +
  geom_line(aes(y=points)) +
  #geom_line(aes(y=points_proj_as_of), linetype="longdash") +
  #geom_line(aes(y=points_pyth_as_of), linetype="dotdash", alpha = .5) +
  #theme(legend.position = "none") +
  labs(y="",x="") +
  facet_wrap(~ player) 
```
