---
title: "Monthly Review"
author: "Tom Kain"
date: "May 25, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
library(plotly)
library(tidyverse)
library(janitor)
library(knitr)
library(glue)
source("R/standings.R")
```

```{r}
picks <- read_csv("data/2019_mlbFutures_picks.csv") %>% 
  clean_names() %>% 
  mutate(pick = row_number(),
         round = (pick / 3) %>% ceiling())

preseason_proj <- picks %>%
  mutate(avg_wins = (proj_538 + proj_fangraphs) / 2,
         points_proj = case_when(
           inverted ~ 162 - avg_wins,
           TRUE ~ avg_wins
         ))

standings <- get_standings(date = "2019-09-01",from = TRUE)
```

```{r include=TRUE, echo=FALSE}
results <-
  preseason_proj %>% 
  select(-division) %>% 
  left_join(standings, by = c("abbrev" = "tm")) %>% 
  mutate(win_perc_proj = avg_wins/162,
         point_perc_proj = if_else(inverted,1-win_perc_proj,win_perc_proj),
         games = w + l,
         points = if_else(inverted,l,w),
         point_perc = points / games,
         w_pace = round_half_up(w_l_percent * 162),
         l_pace = 162-w_pace,
         points_pace = if_else(inverted,l_pace,w_pace),
         w_pyth = round_half_up(pyth_w_l_percent * 162),
         l_pyth = 162-w_pyth,
         points_pyth = if_else(inverted,l_pyth,w_pyth))

expected_points <- results %>% 
  mutate(point_perc_gap = round(point_perc - point_perc_proj,3),
         points_exp = round(point_perc_proj * games,2),
         gap = round(points - points_exp,2)) %>% 
  arrange(abs(point_perc_gap) %>% desc(), points_exp %>% desc()) %>% 
  #filter(abs(gap) >= 2) %>% 
  select(player, team, points, points_exp, gap)

expected_points %>% kable()

expected_points %>% 
  group_by(player) %>% 
  summarize(points = sum(points),
            points_exp = sum(points_exp),
            gap = sum(gap)) %>% 
  arrange(points %>% desc) %>% kable()
```

```{r standings_mid_month, eval=FALSE, include=FALSE}
# use to get standings for a range of dates
standings <- get_standings(date = "2019-08-01",from = TRUE)
standings_sep <- get_standings(date = "2019-09-01",from = TRUE)

standings <-
  standings_sep %>% 
  select(tm:l, rs, ra, since) %>% 
  rename(w_sep = w,
         l_sep = l,
         rs_sep = rs,
         ra_sep = ra,
         thru = since) %>% 
  right_join(standings, "tm") %>% 
  mutate(w = w - w_sep,
         l = l - l_sep,
         rs = rs - rs_sep,
         ra = ra - ra_sep,
         w_l_percent = w / (w + l),
         pyth_w_l_percent = rs^1.81/(rs^1.81 + ra^1.81)
         ) %>% 
  select(tm, w:since, thru, -gb)

```