---
title: "Home Run Derby"
author: "Tom Kain"
date: "7/19/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
library(tidyverse)
library(janitor)
library(knitr)
```

```{r}
derby_raw <- read_csv("data/hr_derby.csv") %>% 
  clean_names()

picks <- tribble(
  ~pick, ~player,
  "Tom", "Joc Pederson",
  "Tom", "Josh Bell",
  "Will", "Pete Alonso",
  "Will", "Matt Chapman",
  "Dad", "Vladimir Guerrero Jr.",
  "Dad", "Ronald Acuna Jr."
)

derby_raw %>% 
  left_join(picks, "player") -> derby

derby_sum <- derby %>% 
  group_by(pick, player) %>% 
  summarize(total_hr = n(),
            max_distance = max(distance)) %>% 
  arrange(total_hr %>% desc)

pick_sum <- derby_sum %>% 
  ungroup() %>% 
  mutate(longest_hr = if_else(max_distance == max(max_distance), 10, 0),
         derby_winner = if_else(player == 'Pete Alonso', 10, 0)) %>% 
  group_by(pick) %>% 
  mutate(points = total_hr + longest_hr + derby_winner) %>% 
  summarize(total_hr = sum(total_hr),
            max_distance = max(max_distance),
            points = sum(points)) %>% 
  mutate(points = round(points / 10 , 1)) %>% 
  filter(!is.na(pick)) %>% 
  arrange(points %>% desc)
```

```{r}
derby_sum %>% kable()
pick_sum %>% kable()
```