---
title: "Team Preseason Projections"
author: "Tom Kain"
date: "7/21/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(plotly)
```

```{r}
projections <- 
  here("data_in", "preseason_projections.csv") %>% 
  read_csv() %>% 
  clean_names()
```

```{r}
points_plot <- 
  projections %>% 
  dplyr::filter(division != 'NL East') %>% 
  ggplot(aes(x=division, y=points, color=division)) +
  geom_jitter(aes(label=team))

ggplotly(points_plot)

wins_plot <- 
  projections %>% 
  dplyr::filter(division != 'NL East') %>% 
  ggplot(aes(x=division, y=wins, color=division)) +
  geom_jitter(aes(label=team))

ggplotly(wins_plot)
```

```{r}

picks <- 
  here("data_in", "preseason_picks.csv") %>% 
  read_csv() %>% 
  clean_names() %>% 
  rename(pick = pick_number)

preseason_picks_with_projections <- 
  picks %>% 
  left_join(projections, by = c("team","division")) %>% 
  select(player, team, points)
  
preseason_picks_with_projections %>% 
  group_by(player) %>% 
  summarize(points = sum(points)) %>% 
  arrange(desc(points))

```

```{r}

picks %>% 
  left_join(preseason_picks_with_projections, by = c("player", "team")) %>% 
  write_csv(here("data_in", "preseasonPicksWithProjections.csv"))

```