---
title: "Midseason Results Tracking"
author: "Tom Kain"
date: "8/5/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(plotly)
library(googlesheets4)
source("R/standings.R")
```

```{r}
team_abbreviation_map <-
  here::here("in", "team_abbrevation_map.csv") %>% 
  readr::read_csv() %>% 
  janitor::clean_names()

picks <-
  here("in", "preseason_picks.csv") %>% 
  read_csv() %>% 
  clean_names() %>% 
  rename(pick = pick_number) %>% 
  left_join(team_abbreviation_map) %>% 
  select(-team_name)

standings <- 
  here::here("in","bref_boxes_20221006.html") %>% 
  get_standings() %>% 
  select(tm:w_l_percent, pyth_w_l_percent)

```

```{r}
games_season <- 162

projected_results <-
  picks %>% 
  left_join(standings) %>% 
  mutate(round = ceiling(pick/3),
         games_played = w+l,
         points = if_else(inverted,l,w),
         w_wp = round_half_up(w_l_percent * games_season),
         l_lp = games_season-w_wp,
         pace_wp = if_else(inverted,l_lp,w_wp),
         w_pyth = round_half_up(pyth_w_l_percent * (games_season-games_played)) + w,
         l_pyth = games_season-w_pyth,
         pace_pyth = if_else(inverted,l_pyth,w_pyth))
```

```{r}
player_pace <- 
  projected_results %>%
  group_by(player) %>% 
  summarize(points = sum(points),
            pace_wp = sum(pace_wp),
            pace_pyth = sum(pace_pyth)) %>% 
  arrange(points %>% desc)

full_standings <- 
  projected_results %>% 
  select(player, team, round, inverted, w, l, games_played, points, pace_wp, pace_pyth) %>% 
  arrange(player, points %>% desc)

player_pace %>% write_csv(here("out", paste0("player_pace-", Sys.Date(), ".csv")))
full_standings %>% write_csv(here("out", paste0("full_standings-", Sys.Date(), ".csv")))
```

```{r}
g4_auth_user <- readr::read_file(here::here("in", "g4_auth.txt"))
google_sheet_url <- 
  "https://docs.google.com/spreadsheets/d/1KPoJM1vvvkDfLdC6ourt9f98zcZYjTFngeAVgxYme3A/edit?usp=sharing"
gs4_auth(g4_auth_user)

player_pace %>% 
  googlesheets4::write_sheet(google_sheet_url, sheet = "Midseason Tracking Summary")
full_standings %>% 
  googlesheets4::write_sheet(google_sheet_url, sheet = "Midseason Tracking Details")
```